import Head from 'next/head';
import Image from 'next/image';
import axios from "axios";
import { useState } from 'react';
import { BsSearch } from 'react-icons/bs';
import Weather from "../Components/Weather";
import Loader from "../Components/Loader";

export default function Home() {

  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const apiCall = `https://api.openweathermap.org/data/2.5/weather?q=${city}&mode=json&units=metric&APPID=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;
  const fetchWeather = e => {
    e.preventDefault();
    setLoading(true);
    axios.get(apiCall)
        .then((response) => {
          setWeather(response.data);
        })
    setCity('');
    setLoading(false);
  };

  if(loading){
      return <Loader/>;
  }
  else {
      return (
          <div>
              <Head>
                  <title>Weather App</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/favicon.ico" />
              </Head>
              {/* Overlay */}
              <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]' />
              {/* BackGround Image */}
              <Image src='http://t0.gstatic.com/licensed-image?q=tbn:ANd9GcQOFSIS0QKpikqYCn77rN2QxT1NnJ56204nUgldcvTh6TurwSAJZcVFc-Ht-OaSDzFw47mA3NKPwKI7Ro_5YD4'
                     layout='fill'
                     className='object-cover'/>
              {/* Search Form */}
              <div className="relative flex justify-between items-center max-w-[500px] w-64 md:w-full m-auto pt-4 text-white z-10">
                  <form onSubmit={fetchWeather} className="flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 rounded-3xl text-white">
                      <div>
                          <input onChange={e => setCity(e.target.value)} type="text" placeholder="Search city" className='bg-transparent border-none text-white focus:outline-none text-2xl'/>
                      </div>
                      <button onClick={fetchWeather} ><BsSearch size={20}/></button>
                  </form>
              </div>
              {/*  Weather Display Section  */}
              {weather.main && <Weather data={weather}/>}

          </div>
      );
  }

}
